### ISSUE TITLE
Incorrect avg_buy_price and/or cf_avg_price value in getPosition response

### ISSUE THREAD

**Issue by cpankaj** [upstox/upstox-nodejs#17]
**## getPosition response doesn't give correct information.**

It sends **_close_price_** valie in **_avg_buy_price_**.
There is no way to know the buy_price of a security.
I am attaching few screenshots
<img width="297" alt="screen shot 2018-02-03 at 6 51 17 pm" src="https://user-images.githubusercontent.com/12436651/35767789-79e028ea-0918-11e8-8ff6-3f796254b40a.png">

Now the same position details from pro.upstox.com web
<img width="1017" alt="screen shot 2018-02-03 at 7 30 26 pm" src="https://user-images.githubusercontent.com/12436651/35767805-bb450c4c-0918-11e8-9100-9d2caeb167d0.png">

**Please note the difference in cf_avg_price value**

**Comment by Rahulzz** [comment]
We hope this message finds you well. We would like to inform you that the issue you reported is related to an outdated version of our API. As a result, we will be closing this issue since it is no longer valid. We understand the importance of staying up-to-date, so we strongly urge you to start planning your migration towards the latest version, v2, of our API. As part of this process, please be aware that our legacy v1 API and SDK are scheduled for deprecation soon.

Exciting news! We are thrilled to announce the release of our brand new V2 API version, bringing along various improvements and enhancements. You can access it at https://upstox.com/uplink/

To ensure a smooth transition, we recommend obtaining the most recent SDK (v2.0.0) by visiting: https://www.npmjs.com/package/upstox-js-sdk/

For your convenience, all the necessary details regarding the API's functionalities can be found in our comprehensive API documentation: https://upstox.com/developer/api-documentation/

We sincerely appreciate your cooperation during this transition period, and our dedicated team is ready to assist you with any queries or support you may need while using the latest version of our API.

Thank you for being part of the Upstox community, and we look forward to providing you with an even better experience with our v2 API.

Best regards,
The Upstox Team
